### ISSUE TITLE
List the members of the batch (read OnbardingBatch contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch6.buidlguidl.com#3]
## Goal

Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #9 )
- Each builder should link to their personal profile (see #8 )

**Comment by carletex** [comment]
I think @JeFlame was also interested as per their Telegram msgs. Tagging you both so you can work on it together!

**Comment by wildanvin** [comment]
Hello, I went ahead and submitted a PR. @JeFlame, we can discuss if you want to change something or implement it in a different way, just let me know 😊

**Comment by JeFlame** [comment]
> Hello, I went ahead and submitted a PR. @JeFlame, we can discuss if you want to change something or implement it in a different way, just let me know 😊

I read your PR. Great job @wildanvin :+1: :+1:
